### ISSUE TITLE
GLib.Error g-unix-error-quark: Too many open files

### ISSUE THREAD

**Issue by hs4842** [slgobinath/gcalendar#10]
I have a dedicated machine that I leave running all the time, and stay logged in all the time. After a day or three of running gcalendar will show only "GLib.Error g-unix-error-quark: Too many open files". I noticed that this is referenced as far back as four months at: [https://cinnamon-spices.linuxmint.com/desklets/view/35](https://cinnamon-spices.linuxmint.com/desklets/view/35).

I haven't checked your source, but it seems that the applet might have a file handle cleanup issue??  This is the only app that does this. No errors noted in the .xsessions-errors file.

**Comment by slgobinath** [comment]
Hi, I investigated the issue and found the problem but fixing it causes several other issues in the desklet. I am working on a proper fix but it may take a while to release.

**Comment by slgobinath** [comment]
Lets track this issue at https://github.com/linuxmint/cinnamon-spices-desklets/issues/558

**Comment by slgobinath** [comment]
Hi,
Can you help me test the fix? If possible, please replace the `~/.local/share/cinnamon/desklets/googleCalendar@javahelps.com/lib/utility.js` by https://raw.githubusercontent.com/slgobinath/cinnamon-spices-desklets/fix-too-many-files-open/googleCalendar%40javahelps.com/files/googleCalendar%40javahelps.com/lib/utility.js and restart Cinnamon to apply the changes.

Let it run for couple of days and let me know if the problem is fixed or not.

Thanks

**Comment by hs4842** [comment]
Got it installed. I'll update you Monday--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 6/4/21, 7:44 AM Gobinath ***@***.***> wrote:

   
  Hi, Can you help me test the fix? If possible, please replace the ***@***.***/lib/utility.js by https://raw.githubusercontent.com/slgobinath/cinnamon-spices-desklets/fix-too-many-files-open/googleCalendar%40javahelps.com/files/googleCalendar%40javahelps.com/lib/utility.js and restart Cinnamon to apply the changes. 
  Let it run for couple of days and let me know if the problem is fixed or not. 
  Thanks

**Comment by hs4842** [comment]
I have been running with this patch for two days and no more crashing. I think you may have fixed the problem. I'll let you know if it happens again. My recommendation is to commit it as an update.

Thanks for all your programming efforts and fixes.

 
 

Sent: Friday, June 04, 2021 at 7:44 AM

**Comment by slgobinath** [comment]
Great thanks for confirming. I will ask the repo maintainers to merge the fix.

**Comment by codeunifier** [comment]
I'm getting this error now randomly. Not sure what happened that caused it. Removing / replacing and uninstalling / reinstalling the desklet didn't fix the issue. I tried replacing my utility.js file with the one you linked above just in case, which I'm sure was involved in the merge, and that didn't resolve it either. Do you have any other recommendations on how to recover from this issue?

**Comment by hs4842** [comment]
I loaded the Restart Cinnamon applet to restart the environment when this happens. My guess is a memory leak in the API or continued and non-reused file descriptor that either needs to be closed or saved for reuse. I don't have the code to review the desklette but I'll see if I can download it and review things.--A workman is worthy of his wages...On 10/4/21, 6:51 PM CodeUnifier ***@***.***> wrote:

   
  I'm getting this error now randomly. Not sure what happened that caused it. Removing / replacing and uninstalling / reinstalling the desklet didn't fix the issue. I tried replacing my utility.js file with the one you linked above just in case, which I'm sure was involved in the merge, and that didn't resolve it either. Do you have any other recommendations on how to recover from this issue?

**Comment by codeunifier** [comment]
The Restart Cinnamon applet is phenomenal! Super helpful. Came back to this today and after a reboot everything is working as expected, so I'm not sure what happened there. I'll let you know if I come across a way to reproduce it
