### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by TimBrit** [slgobinath/gcalendar#11]
Hi there i frequently get an error - Unknown Error Glib.error g-unix-error-quark: Too many open files. 
Reloading the desklet does nothing, and the only way to resolve is to restart the desktop.

**Comment by slgobinath** [comment]
Hi,the fix for this issue is merged couple of days ago. Could you pls update the desklet and see if it happens again?
After updating the desklet, please restart the desktop once.
