### ISSUE TITLE
Not showing all of my calendars

### ISSUE THREAD

**Issue by sbhhdp** [slgobinath/gcalendar#12]
Hey can you tell if it is the way it is meant to work. 

This is what gcalendar lists.
![image](https://user-images.githubusercontent.com/44867453/124607747-c1500780-de8b-11eb-967f-51c0ef9fcaf6.png)

This is what google calendar actually shows. Reminders and tasks are not showing up in gaclendar.
![image](https://user-images.githubusercontent.com/44867453/124608349-4804e480-de8c-11eb-8b36-60684864583a.png)

**Comment by slgobinath** [comment]
Hi, Yup Google does not provide an API to retrieve Tasks and Reminders. At the moment, gcalendar can show only the calendars.

Closing this issue in favour of https://github.com/slgobinath/gcalendar/issues/3
