### ISSUE TITLE
Desklet is not working properly

### ISSUE THREAD

**Issue by KulagaIvan** [slgobinath/gcalendar#14]
Gcalendar in terminal is working, but desklet not.

**Comment by MarHaj** [comment]
I've got exactly the same issue as @KulagaIvan  (Cinnamon 4.4.8 on Mint 19.3): in terminal working perfectly, desklet reports "gcalendar is not authorized"

- Restarting did not help.
- Uninstalling and installing desklet via standard Mint desklet utility did not help either.

Rem: desklet stops working after the last update last week.

**Comment by KulagaIvan** [comment]
Desklet died?

**Comment by KulagaIvan** [comment]
![Снимок экрана от 2021-09-14 15-36-56](https://user-images.githubusercontent.com/89584676/133258791-f833c9fb-80a0-4817-b369-998a3c427e5a.png)

**Comment by KulagaIvan** [comment]
Everything in one picture.

**Comment by KulagaIvan** [comment]
![Снимок экрана от 2021-09-14 15-39-42](https://user-images.githubusercontent.com/89584676/133259091-e4566b7b-ffca-4f69-9cb2-80790f1644df.png)

**Comment by slgobinath** [comment]
@KulagaIvan what is the Cinnamon version?

**Comment by gabrielebianchi** [comment]
I have exactly  the same issue described by @Kulagalvan. My version of Cinnamon is 4.4.8 in Mint 19.3. I have tried what described by @MarHaj, but even for me without any success.  

Thanks for you app and for any help.
Gabriele Bianchi

**Comment by KulagaIvan** [comment]
System:    Host: kulaga-Inspiron-5570 Kernel: 5.0.0-32-generic x86_64 bits: 64 compiler: gcc 
           v: 7.4.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic

**Comment by slgobinath** [comment]
Hi, It looks like, one of my recent change is not compatible with older Cinnamon. I will look into this issue.

**Comment by KulagaIvan** [comment]
Alas...
Kernel: 5.4.0-86-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.0.5 
           wm: muffin dm: LightDM Distro: Linux Mint 20.2 Uma base: Ubuntu 20.04 focal 
Not working too.

**Comment by KulagaIvan** [comment]
I'm so sorry.
Everything worked well on Mint 20.2

**Comment by slgobinath** [comment]
Hi,
I've released a fix to the applet https://github.com/linuxmint/cinnamon-spices-desklets/pull/707 I'd appreciate it if you can test it and let me know if the problem has been fixed.

**Comment by MarHaj** [comment]
> Hi, I've released a fix to the applet [linuxmint/cinnamon-spices-desklets#707](https://github.com/linuxmint/cinnamon-spices-desklets/pull/707) I'd appreciate it if you can test it and let me know if the problem has been fixed.

Well, it works for me (Cinnamon 4.4.8 on Mint 19.3) again. Many thanks @slgobinath !!!

**Comment by slgobinath** [comment]
@MarHaj thanks for confirming. I will track the new bug in #15
