### ISSUE TITLE
unable to add PPA "PPA does not support noble"

### ISSUE THREAD

**Issue by Owweeee** [slgobinath/gcalendar#23]
I've tried to reinstall gcalendar after upgrading my system to Mint 22 and get the error that

`Cannot add PPA: ''This PPA does not support noble''. `

**Comment by vladimirzb** [comment]
Same problem here

**Comment by slgobinath** [comment]
Released to the latest Ubuntu releases. Please try again:
```
sudo add-apt-repository ppa:slgobinath/gcalendar
sudo apt update
sudo apt install gcalendar
```
