### ISSUE TITLE
Q: How does this code interact with the gcalendar desklet?

### ISSUE THREAD

**Issue by rudrrayan** [slgobinath/gcalendar#7]
I want to create a fork with some code that highlights the text on the desklet

**Comment by slgobinath** [comment]
Hi,
Here is the source code of the desklet UI https://github.com/linuxmint/cinnamon-spices-desklets/tree/master/googleCalendar%40javahelps.com

It talks to the `gcalendar` using the command line api as shown here https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/googleCalendar%40javahelps.com/files/googleCalendar%40javahelps.com/desklet.js#L202

Here is the method that creates UI entry for each calendar event https://github.com/linuxmint/cinnamon-spices-desklets/blob/master/googleCalendar%40javahelps.com/files/googleCalendar%40javahelps.com/desklet.js#L240

**Comment by slgobinath** [comment]
If you make a generic feature that may help others, please raise a PR at https://github.com/linuxmint/cinnamon-spices-desklets/pulls
